/** Pixel-art Clerk theme — used as fallback if any Clerk UI surfaces. */
export const clerkAppearance = {
  layout: {
    socialButtonsPlacement: 'top',
    socialButtonsVariant: 'blockButton',
    showOptionalFields: false,
    logoPlacement: 'none',
    privacyPageUrl: undefined,
    termsPageUrl: undefined,
    helpPageUrl: undefined,
  },
  variables: {
    colorPrimary: '#FFCC00',
    colorBackground: '#FFFEF5',
    colorText: '#141414',
    colorTextSecondary: '#525252',
    colorInputBackground: '#FFFFFF',
    colorInputText: '#141414',
    borderRadius: '0.75rem',
    fontFamily: 'var(--font-outfit), system-ui, sans-serif',
    fontFamilyButtons: 'var(--font-outfit), system-ui, sans-serif',
  },
  elements: {
    card: {
      border: '4px solid #141414',
      boxShadow: '4px 4px 0 #141414',
      borderRadius: '1rem',
    },
    modalContent: {
      border: '4px solid #141414',
      boxShadow: '8px 8px 0 #141414',
      borderRadius: '1rem',
    },
    headerTitle: {
      fontFamily: 'var(--font-pixel), monospace',
      fontSize: '13px',
      letterSpacing: '-0.02em',
    },
    socialButtonsBlockButton: {
      border: '3px solid #141414',
      boxShadow: '2px 2px 0 #141414',
      borderRadius: '0.75rem',
      fontWeight: '700',
    },
    footer: { display: 'none' },
    footerAction: { display: 'none' },
    dividerRow: { display: 'none' },
    form: { display: 'none' },
    formFieldRow: { display: 'none' },
    identityPreview: { display: 'none' },
    headerSubtitle: { display: 'none' },
    logoBox: { display: 'none' },
    logoImage: { display: 'none' },
    devBar: { display: 'none' },
    footerPages: { display: 'none' },
    internal: { display: 'none' },
  },
};
